name: genkit_vertexai
description: Vertex AI plugin for Genkit Dart.
resolution: workspace
version: 0.2.7
repository: https://github.com/genkit-ai/genkit-dart
license: Apache-2.0

environment:
  sdk: ^3.10.0

dependencies:
  anthropic_sdk_dart: ^2.0.0
  genkit: ^0.13.2
  genkit_anthropic: ^0.2.4
  genkit_google_genai: ^0.2.7
  genkit_vertex_auth: ^0.1.7
  http: ^1.6.0
  meta: ^1.17.0
  schemantic: ^0.1.3

dev_dependencies:
  test: ^1.29.0
